# DSO 
cam0:
  cam_cx: 631
  cam_cy: 510
  cam_d0: 0.933271000000000
  cam_d1: 0
  cam_d2: 0
  cam_d3: 0 
  cam_fx: 447
  cam_fy: 447
  cam_height: 1024
  cam_model: ATAN
  cam_width: 1280
  rx: 0.0
  ry: 0.0
  rz: 0.0
  tx: 0.0
  ty: 0.0
  tz: 0.0
images_subfolder: images/